### ISSUE TITLE
Location data and forecasts not correct

### ISSUE THREAD

**Issue by dustball62** [mlamberts78/weather-chart-card#117]
Hello- I'm trying to figure out how and were this chart/card pulls the forecast data from.  I'm seeing very wrong data and I'd like to see if I can correct it.  Looking at the entity- i see `attribution: Weather forecast from met.no, delivered by the Norwegian Meteorological Institu` but I dont know what its using to gather my local data.  Thanks in advance for your help
Dusty

**Comment by mlamberts78** [comment]
Hello,

the weather cart card only displays the data provided by the weather integration you selected. If you have wrong data, it is caused by the weather integration and not by the card.

You can check your weather integration output via:
Developer tools - services - Get weather forecast.

More information can be found here: https://www.home-assistant.io/integrations/weather/

**Comment by dustball62** [comment]
Ok I understand now, thanks for pointing me to that. I scoured the readme  and all the python code and found nothing to indicate that I had to have preexisting entities for forecasting.  Plus the fact it was presenting data on the card led me to believe something was built in that I couldnt see.  I already pull in my local data but i was looking to add forecasting, I see new I need to add a forecasting service and associated entities.

Thanks again
